### ISSUE TITLE
Roadmap for 4.X

### ISSUE THREAD

**Issue by greeny** [php-mail-client/Client#1]
/cc @jkuchar 

- [ ] use Nette coding style
- [ ] rename namespace to `greeny\MailClient`
- [ ] remove occurences of `$this->mailboxes || $this->initialize()` and similar, replace with standart `if`
- [ ] merge #13 and #14 or use parts from them
- [ ] write unit tests
- [ ] test different mail providers for differences in server communication
- [ ] replace `Contact` and `ContactList` with some external service, like `ContactParser`
- [ ] make `ContactParser` independent on `imap_*` functions
- [ ] remove `Selection::mailIndexes` (use native `ArrayIterator`)
- [ ] try refactor Mail to split from Connection (Doctrine-like access)
- [ ] drivers - move to separate repos (keep `IDriver` in `Client` repo)
    - [ ] `SocketDriver` - direct connect through socket to IMAP server
    - [ ] `ImapDriver` - ? imap extension in PHP - for back compatibility?
    - [ ] `EwsDriver` - https://packagist.org/packages/php-ews/php-ews
    - [ ] `HordeDriver` - http://dev.horde.org/imap_client
