### ISSUE TITLE
Roadmap for version 4.X

### ISSUE THREAD

**Issue by greeny** [php-mail-client/Client#15]
- [x] use Nette coding style
- [x] rename namespace to ~~`greeny\MailClient`~~ `PhpMailClient`
- [x] remove occurences of `$this->mailboxes || $this->initialize()` and similar, replace with standart `if`
- [ ] merge #13 and #14 or use parts from them
- [ ] write unit tests
- [ ] test different mail providers for differences in server communication
- [ ] replace `Contact` and `ContactList` with some external service, like `ContactParser`
- [ ] make `ContactParser` independent on `imap_*` functions
- [x] remove `Selection::mailIndexes` (use native `ArrayIterator`)
- [ ] try refactor Mail to split from Connection (Doctrine-like access)
- [ ] `SocketDriver`
